Document: ohmono-dev
Title: Debian ohmono-dev Manual
Author: <insert document author here>
Abstract: This manual describes what ohmono-dev is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ohmono-dev/ohmono-dev.sgml.gz

Format: postscript
Files: /usr/share/doc/ohmono-dev/ohmono-dev.ps.gz

Format: text
Files: /usr/share/doc/ohmono-dev/ohmono-dev.text.gz

Format: HTML
Index: /usr/share/doc/ohmono-dev/html/index.html
Files: /usr/share/doc/ohmono-dev/html/*.html
