Document: ohgtksharp
Title: Debian ohgtksharp Manual
Author: <insert document author here>
Abstract: This manual describes what ohgtksharp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ohgtksharp/ohgtksharp.sgml.gz

Format: postscript
Files: /usr/share/doc/ohgtksharp/ohgtksharp.ps.gz

Format: text
Files: /usr/share/doc/ohgtksharp/ohgtksharp.text.gz

Format: HTML
Index: /usr/share/doc/ohgtksharp/html/index.html
Files: /usr/share/doc/ohgtksharp/html/*.html
