#!/bin/sh
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
apt-get -qy update && apt-get -qy install ohwidget --force-yes  >> /var/log/ohos-update.log && apt-get -qy --force-yes install ohos  >> /var/log/ohos-update.log && apt-get -qy install ntp && apt-get -qy clean && apt-get -qy autoclean