#!/bin/sh

portal="10.2.8.229"

get_mac() {

        mac=$(ifconfig eth0) && mac=${mac#*HWaddr } && mac=${mac%% *}

        thirdoctet=$(echo $mac | cut -d ':' -f 5)
        lastoctet=$(echo $mac | cut -d ':' -f 6)

}

get_lun() {

       /sbin/iscsiadm --mode discovery --type sendtargets --portal ${portal}
}

set_lun() {
	/sbin/iscsiadm --mode node --portal ${float_ip} --login 
}

mount_lun() {
	mount /dev/disk/by-path/ /root
}



get_mac
get_lun
set_lun
mount_lun