#!/bin/bash

NAME=ohos

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

if [[ "$MDNS_ACTIVE" == 'yes' ]]
then
        /usr/bin/custom-mdns $MDNS_ARGS;
fi

if [[ "$NBD_CLIENT" == 'yes' ]]
then
	/usr/bin/nbd-setup $NBD_ARGS;
fi