Document: ohmono
Title: Debian ohmono Manual
Author: <insert document author here>
Abstract: This manual describes what ohmono is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ohmono/ohmono.sgml.gz

Format: postscript
Files: /usr/share/doc/ohmono/ohmono.ps.gz

Format: text
Files: /usr/share/doc/ohmono/ohmono.text.gz

Format: HTML
Index: /usr/share/doc/ohmono/html/index.html
Files: /usr/share/doc/ohmono/html/*.html
