#!/bin/sh
### BEGIN INIT INFO
# Provides:          wdtstop
# Required-Start:    $local_fs mountkernfs
# Required-Stop:
# X-Start-Before:    networking
# Default-Start:     S
# Default-Stop:      
# Short-Description: Disables the Kirkwood watchdog
# Description:       Debian init script to disable the Kirkwood watchdog
### END INIT INFO

# Author: Openhome <admin@openhome.org>

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Disable Kirkwood watchdog: " # Introduce a short description here
NAME=wdtstop               # Introduce the short server's name here
SCRIPTNAME=/etc/init.d/$NAME
WDT_DEV=/dev/wdt_temp


# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
    mknod $WDT_DEV c 10 130
    echo -n 'V' > $WDT_DEV
    rm $WDT_DEV
}

case "$1" in
  start)
    log_begin_msg "Disabling Kirkwood watchdog ..."
    do_start
    log_end_msg 0
    ;;

  *)
    echo "Usage: $SCRIPTNAME start" >&2
    exit 3
    ;;
esac

exit 0
