Document: oh-sheeva-setup
Title: Debian oh-sheeva-setup Manual
Author: <insert document author here>
Abstract: This manual describes what oh-sheeva-setup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/oh-sheeva-setup/oh-sheeva-setup.sgml.gz

Format: postscript
Files: /usr/share/doc/oh-sheeva-setup/oh-sheeva-setup.ps.gz

Format: text
Files: /usr/share/doc/oh-sheeva-setup/oh-sheeva-setup.text.gz

Format: HTML
Index: /usr/share/doc/oh-sheeva-setup/html/index.html
Files: /usr/share/doc/oh-sheeva-setup/html/*.html
